### ISSUE TITLE
没办法删除回复他人帖子的回复

### ISSUE THREAD

**Issue by Actuallymax** [gengchen528/douEdit#5]
可以删掉自己发的贴子里面的回复，别人发的贴子会报错

(node:7313) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'emit' of undefined
    at req.then.error (/home/hy/douEdit/src/controller.js:118:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7313) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)

**Comment by gengchen528** [comment]
因为无法确定你的回复在别人帖子的页数，默认是从第一页开始，所以会遇到这个问题
